# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('leo-satellite-example', ['leo-satellite'])
    obj.source = 'leo-satellite-example.cc'

    obj = bld.create_ns3_program('mobility-example', ['leo-satellite'])
    obj.source = 'mobility-example.cc'
    
    obj = bld.create_ns3_program('qos-aware-routing', ['leo-satellite'])
    obj.source = 'qos_aware_routing.cc'

    obj = bld.create_ns3_program('plane-dijkstra', ['leo-satellite'])
    obj.source = 'plane_dijkstra.cc'

    obj = bld.create_ns3_program('sdra', ['leo-satellite'])
    obj.source = 'sdra.cc'

    obj = bld.create_ns3_program('k-shortest-paths', ['leo-satellite'])
    obj.source = 'k_shortest_paths.cc'
    

